import "server-only";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { marked } from "marked";

/**
 * Articles.
 *
 * Metadata lives here; the body of each one is a markdown file under
 * content/articles/<slug>.md. Markdown is rendered to HTML at build time
 * (this module is server-only), so `marked` never reaches the browser.
 *
 * To add an article: drop a new .md file in content/articles, add an entry
 * below, and generate a thumbnail with scripts/build-article-art.mjs.
 * Order here is the order shown on the homepage — the first is featured.
 */
export type Article = {
  slug: string;
  /** Shown on the card and as the page <h1>. */
  title: string;
  /** Gold-highlighted run at the end of the page heading. */
  titleHighlight: string;
  excerpt: string;
  /** ISO date. Also the "last updated" line on the article page. */
  date: string;
  /** Short label used on the card and in the hero strip. */
  topic: string;
};

export const ARTICLES: Article[] = [
  {
    slug: "what-asmongold-is-playing-2026",
    title: "What Asmongold Is Playing in 2026: The Full List and His Verdicts",
    titleHighlight: "His Verdicts",
    excerpt:
      "The running list of everything Zack has sunk real time into this year, with his verdict on each — from a 10/10 for Clair Obscur to the WoW expansion that finally gave players a home.",
    date: "2026-07-21",
    topic: "Games",
  },
  {
    slug: "asmongold-on-gta-6",
    title: "Asmongold on GTA 6: Every Take Ahead of the November 19 Launch",
    titleHighlight: "Every Take",
    excerpt:
      "He called the $100 price ceiling back in 2023, and the Ultimate edition proved him right. Everything Zack has said about the biggest launch of the year, from pricing to the console-only release.",
    date: "2026-07-21",
    topic: "GTA 6",
  },
  {
    slug: "where-to-watch-asmongold",
    title: "Where to Watch Asmongold: Twitch, Kick, Rumble, and the Multistream Era",
    titleHighlight: "Multistream Era",
    excerpt:
      "Three platforms at once, plus the clips channel that catches what you missed. How he got here, and why it made him the fourth most-watched streamer in the world.",
    date: "2026-07-21",
    topic: "Channels",
  },
  {
    slug: "why-asmongold-left-otk",
    title: "Why Asmongold Stepped Away From OTK",
    titleHighlight: "From OTK",
    excerpt:
      "He co-founded it, then left in two stages. The straight version of what happened, in his own words — and the basic math that made leaving the clean solution.",
    date: "2026-07-21",
    topic: "OTK",
  },
];

export function getArticle(slug: string): Article | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}

/** Thumbnail path for an article, generated by scripts/build-article-art.mjs. */
export function articleImage(slug: string, width: 800 | 1400 = 800) {
  return `/assets/articles/${slug}-${width}`;
}

/** Read the markdown body and render it to HTML. Build-time only. */
export function renderArticleBody(slug: string): string {
  const path = join(process.cwd(), "content", "articles", `${slug}.md`);
  const md = readFileSync(path, "utf8");
  return marked.parse(md, { async: false }) as string;
}
